# -*- coding: utf-8 -*-
"""OIBSIP_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUeQv_oJfsFSrnoxyF5ssvH__I7kuQ_9
"""

from google.colab import files
import pandas as pd

# Upload the file
uploaded = files.upload()

df1 = pd.read_csv('Unemployment in India.csv')
df2 = pd.read_csv('Unemployment_Rate_upto_11_2020.csv')
df1

# Display the first few rows of each DataFrame
print("Unemployment in India.csv:")
print(df1.head())
print("\nUnemployment_Rate_upto_11_2020.csv:")
print(df2.head())

# Check the structure and basic info of the first dataset
print("Info for Unemployment in India.csv:")
print(df1.info())
print(df1.describe())

# Check for missing values in the first dataset
print("Missing values in Unemployment in India.csv:")
print(df1.isnull().sum())

# Check the structure and basic info of the second dataset
print("Info for Unemployment_Rate_upto_11_2020.csv:")
print(df2.info())
print(df2.describe())

# Check for missing values in the second dataset
print("Missing values in Unemployment_Rate_upto_11_2020.csv:")
print(df2.isnull().sum())

# Fill missing values or drop them if necessary
df1.fillna(method='ffill', inplace=True)
df2.fillna(method='ffill', inplace=True)

# Ensure 'Date' columns are in string format before converting to datetime
df1[' Date'] = df1[' Date'].astype(str)
df2[' Date'] = df2[' Date'].astype(str)

# Convert 'Date' columns to datetime format
df1[' Date'] = pd.to_datetime(df1[' Date'], errors='coerce')
df2[' Date'] = pd.to_datetime(df2[' Date'], errors='coerce')

# Verify the changes
print(df1.head())
print(df2.head())

import matplotlib.pyplot as plt

# Plot the unemployment rate from the first dataset
plt.figure(figsize=(12, 6))
plt.plot(df1[' Date'], df1[' Estimated Unemployment Rate (%)'], label='Unemployment Rate (India)')
plt.title('Unemployment Rate in India Over Time')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

# Plot the unemployment rate from the second dataset
plt.figure(figsize=(12, 6))
plt.plot(df2[' Date'], df2[' Estimated Unemployment Rate (%)'], label='Unemployment Rate (upto 11/2020)')
plt.title('Unemployment Rate upto 11/2020')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

# Plot the labor participation rate from the first dataset
plt.figure(figsize=(12, 6))
plt.plot(df1[' Date'], df1[' Estimated Labour Participation Rate (%)'], label='Labour Participation Rate (India)')
plt.title('Labour Participation Rate in India Over Time')
plt.xlabel('Date')
plt.ylabel('Labour Participation Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

# Plot the labor participation rate from the second dataset
plt.figure(figsize=(12, 6))
plt.plot(df2[' Date'], df2[' Estimated Labour Participation Rate (%)'], label='Labour Participation Rate (upto 11/2020)')
plt.title('Labour Participation Rate upto 11/2020')
plt.xlabel('Date')
plt.ylabel('Labour Participation Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

# Histogram of Unemployment Rate
plt.figure(figsize=(10, 6))
plt.hist(df1[' Estimated Unemployment Rate (%)'], bins=20, alpha=0.7, label='Unemployment Rate (India)')
plt.xlabel('Unemployment Rate (%)')
plt.ylabel('Frequency')
plt.title('Distribution of Unemployment Rate in India')
plt.legend()
plt.show()

# Box plot of Unemployment Rate by Region
plt.figure(figsize=(14, 8))
df1.boxplot(column=' Estimated Unemployment Rate (%)', by='Region', rot=90)
plt.title('Unemployment Rate by Region')
plt.suptitle('')
plt.xlabel('Region')
plt.ylabel('Unemployment Rate (%)')
plt.show()

# Scatter plot of Unemployment Rate vs. Labour Participation Rate
plt.figure(figsize=(10, 6))
plt.scatter(df1[' Estimated Labour Participation Rate (%)'], df1[' Estimated Unemployment Rate (%)'], alpha=0.5)
plt.title('Unemployment Rate vs. Labour Participation Rate')
plt.xlabel('Labour Participation Rate (%)')
plt.ylabel('Unemployment Rate (%)')
plt.grid(True)
plt.show()